FROM grafana/grafana:6.3.6

COPY ./entrypoint.sh /entrypoint.sh

USER root

RUN \
  apt-get update \
  && apt-get -y install gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN chmod a+x /entrypoint.sh
  
ENTRYPOINT [ "/entrypoint.sh" ]
