// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laudry_state.proto

package com.microservices.laundrymanagementapi.messages;

public final class LaudryStateProto {
  private LaudryStateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LaudryStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LaudryState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 orderId = 1;</code>
     */
    int getOrderId();

    /**
     * <code>int64 queueWaitingTime = 2;</code>
     */
    long getQueueWaitingTime();

    /**
     * <code>int32 version = 3;</code>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code LaudryState}
   */
  public  static final class LaudryState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LaudryState)
      LaudryStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LaudryState.newBuilder() to construct.
    private LaudryState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LaudryState() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LaudryState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LaudryState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              orderId_ = input.readInt32();
              break;
            }
            case 16: {

              queueWaitingTime_ = input.readInt64();
              break;
            }
            case 24: {

              version_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservices.laundrymanagementapi.messages.LaudryStateProto.internal_static_LaudryState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservices.laundrymanagementapi.messages.LaudryStateProto.internal_static_LaudryState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState.class, com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private int orderId_;
    /**
     * <code>int32 orderId = 1;</code>
     */
    public int getOrderId() {
      return orderId_;
    }

    public static final int QUEUEWAITINGTIME_FIELD_NUMBER = 2;
    private long queueWaitingTime_;
    /**
     * <code>int64 queueWaitingTime = 2;</code>
     */
    public long getQueueWaitingTime() {
      return queueWaitingTime_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <code>int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderId_ != 0) {
        output.writeInt32(1, orderId_);
      }
      if (queueWaitingTime_ != 0L) {
        output.writeInt64(2, queueWaitingTime_);
      }
      if (version_ != 0) {
        output.writeInt32(3, version_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, orderId_);
      }
      if (queueWaitingTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, queueWaitingTime_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState)) {
        return super.equals(obj);
      }
      com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState other = (com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState) obj;

      if (getOrderId()
          != other.getOrderId()) return false;
      if (getQueueWaitingTime()
          != other.getQueueWaitingTime()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId();
      hash = (37 * hash) + QUEUEWAITINGTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getQueueWaitingTime());
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LaudryState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LaudryState)
        com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microservices.laundrymanagementapi.messages.LaudryStateProto.internal_static_LaudryState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microservices.laundrymanagementapi.messages.LaudryStateProto.internal_static_LaudryState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState.class, com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState.Builder.class);
      }

      // Construct using com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        orderId_ = 0;

        queueWaitingTime_ = 0L;

        version_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microservices.laundrymanagementapi.messages.LaudryStateProto.internal_static_LaudryState_descriptor;
      }

      @java.lang.Override
      public com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState getDefaultInstanceForType() {
        return com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState.getDefaultInstance();
      }

      @java.lang.Override
      public com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState build() {
        com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState buildPartial() {
        com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState result = new com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState(this);
        result.orderId_ = orderId_;
        result.queueWaitingTime_ = queueWaitingTime_;
        result.version_ = version_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState) {
          return mergeFrom((com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState other) {
        if (other == com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState.getDefaultInstance()) return this;
        if (other.getOrderId() != 0) {
          setOrderId(other.getOrderId());
        }
        if (other.getQueueWaitingTime() != 0L) {
          setQueueWaitingTime(other.getQueueWaitingTime());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int orderId_ ;
      /**
       * <code>int32 orderId = 1;</code>
       */
      public int getOrderId() {
        return orderId_;
      }
      /**
       * <code>int32 orderId = 1;</code>
       */
      public Builder setOrderId(int value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 orderId = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = 0;
        onChanged();
        return this;
      }

      private long queueWaitingTime_ ;
      /**
       * <code>int64 queueWaitingTime = 2;</code>
       */
      public long getQueueWaitingTime() {
        return queueWaitingTime_;
      }
      /**
       * <code>int64 queueWaitingTime = 2;</code>
       */
      public Builder setQueueWaitingTime(long value) {
        
        queueWaitingTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 queueWaitingTime = 2;</code>
       */
      public Builder clearQueueWaitingTime() {
        
        queueWaitingTime_ = 0L;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 3;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 3;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LaudryState)
    }

    // @@protoc_insertion_point(class_scope:LaudryState)
    private static final com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState();
    }

    public static com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LaudryState>
        PARSER = new com.google.protobuf.AbstractParser<LaudryState>() {
      @java.lang.Override
      public LaudryState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LaudryState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LaudryState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LaudryState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.microservices.laundrymanagementapi.messages.LaudryStateProto.LaudryState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LaudryState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LaudryState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022laudry_state.proto\"I\n\013LaudryState\022\017\n\007o" +
      "rderId\030\001 \001(\005\022\030\n\020queueWaitingTime\030\002 \001(\003\022\017" +
      "\n\007version\030\003 \001(\005BC\n/com.microservices.lau" +
      "ndrymanagementapi.messagesB\020LaudryStateP" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LaudryState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LaudryState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LaudryState_descriptor,
        new java.lang.String[] { "OrderId", "QueueWaitingTime", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
