// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order_detail.proto

package com.microservices.laundrymanagementapi.messages;

public final class OrderDetailProto {
  private OrderDetailProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 detailId = 1;</code>
     */
    int getDetailId();

    /**
     * <code>int32 weight = 2;</code>
     */
    int getWeight();

    /**
     * <code>int64 duration = 3;</code>
     */
    long getDuration();
  }
  /**
   * Protobuf type {@code OrderDetail}
   */
  public  static final class OrderDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderDetail)
      OrderDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderDetail.newBuilder() to construct.
    private OrderDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderDetail() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrderDetail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              detailId_ = input.readInt32();
              break;
            }
            case 16: {

              weight_ = input.readInt32();
              break;
            }
            case 24: {

              duration_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microservices.laundrymanagementapi.messages.OrderDetailProto.internal_static_OrderDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microservices.laundrymanagementapi.messages.OrderDetailProto.internal_static_OrderDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail.class, com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail.Builder.class);
    }

    public static final int DETAILID_FIELD_NUMBER = 1;
    private int detailId_;
    /**
     * <code>int32 detailId = 1;</code>
     */
    public int getDetailId() {
      return detailId_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 2;
    private int weight_;
    /**
     * <code>int32 weight = 2;</code>
     */
    public int getWeight() {
      return weight_;
    }

    public static final int DURATION_FIELD_NUMBER = 3;
    private long duration_;
    /**
     * <code>int64 duration = 3;</code>
     */
    public long getDuration() {
      return duration_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (detailId_ != 0) {
        output.writeInt32(1, detailId_);
      }
      if (weight_ != 0) {
        output.writeInt32(2, weight_);
      }
      if (duration_ != 0L) {
        output.writeInt64(3, duration_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (detailId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, detailId_);
      }
      if (weight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, weight_);
      }
      if (duration_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, duration_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail)) {
        return super.equals(obj);
      }
      com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail other = (com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail) obj;

      if (getDetailId()
          != other.getDetailId()) return false;
      if (getWeight()
          != other.getWeight()) return false;
      if (getDuration()
          != other.getDuration()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DETAILID_FIELD_NUMBER;
      hash = (53 * hash) + getDetailId();
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getWeight();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDuration());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderDetail)
        com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microservices.laundrymanagementapi.messages.OrderDetailProto.internal_static_OrderDetail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microservices.laundrymanagementapi.messages.OrderDetailProto.internal_static_OrderDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail.class, com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail.Builder.class);
      }

      // Construct using com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        detailId_ = 0;

        weight_ = 0;

        duration_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microservices.laundrymanagementapi.messages.OrderDetailProto.internal_static_OrderDetail_descriptor;
      }

      @java.lang.Override
      public com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail getDefaultInstanceForType() {
        return com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail.getDefaultInstance();
      }

      @java.lang.Override
      public com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail build() {
        com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail buildPartial() {
        com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail result = new com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail(this);
        result.detailId_ = detailId_;
        result.weight_ = weight_;
        result.duration_ = duration_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail) {
          return mergeFrom((com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail other) {
        if (other == com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail.getDefaultInstance()) return this;
        if (other.getDetailId() != 0) {
          setDetailId(other.getDetailId());
        }
        if (other.getWeight() != 0) {
          setWeight(other.getWeight());
        }
        if (other.getDuration() != 0L) {
          setDuration(other.getDuration());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int detailId_ ;
      /**
       * <code>int32 detailId = 1;</code>
       */
      public int getDetailId() {
        return detailId_;
      }
      /**
       * <code>int32 detailId = 1;</code>
       */
      public Builder setDetailId(int value) {
        
        detailId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 detailId = 1;</code>
       */
      public Builder clearDetailId() {
        
        detailId_ = 0;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <code>int32 weight = 2;</code>
       */
      public int getWeight() {
        return weight_;
      }
      /**
       * <code>int32 weight = 2;</code>
       */
      public Builder setWeight(int value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 weight = 2;</code>
       */
      public Builder clearWeight() {
        
        weight_ = 0;
        onChanged();
        return this;
      }

      private long duration_ ;
      /**
       * <code>int64 duration = 3;</code>
       */
      public long getDuration() {
        return duration_;
      }
      /**
       * <code>int64 duration = 3;</code>
       */
      public Builder setDuration(long value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 duration = 3;</code>
       */
      public Builder clearDuration() {
        
        duration_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OrderDetail)
    }

    // @@protoc_insertion_point(class_scope:OrderDetail)
    private static final com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail();
    }

    public static com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderDetail>
        PARSER = new com.google.protobuf.AbstractParser<OrderDetail>() {
      @java.lang.Override
      public OrderDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderDetail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.microservices.laundrymanagementapi.messages.OrderDetailProto.OrderDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022order_detail.proto\"A\n\013OrderDetail\022\020\n\010d" +
      "etailId\030\001 \001(\005\022\016\n\006weight\030\002 \001(\005\022\020\n\010duratio" +
      "n\030\003 \001(\003BC\n/com.microservices.laundrymana" +
      "gementapi.messagesB\020OrderDetailProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OrderDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderDetail_descriptor,
        new java.lang.String[] { "DetailId", "Weight", "Duration", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
