{
 "title": "TC tech metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "{\"find\":\"terms\", \"field\":\"instance.keyword\"}"
   },
   {
    "name": "endpoint",
    "query": "{\"find\":\"terms\", \"field\":\"uri.keyword\", \"query\":\"name:CoordinatorController AND instance.keyword:$instance\"}"
   },
   { "name": "publish_rate", "query": "${metrics_publish_rate}" }
  ]
 },
 "panels": [
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:system_cpu_usage AND instance.keyword:$instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(name:jvm_memory_*) AND instance.keyword:$instance AND NOT name:jvm_memory_max",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Gc metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:jvm_gc_memory_* AND instance.keyword:$instance",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$endpoint total time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "repeat": "endpoint",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "uri.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$endpoint mean",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "repeat": "endpoint",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      },
      {
       "field": "sum",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "name": "count", "pipelineAgg": "1" },
        { "name": "total", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "params.count == 0 ? 0 : params.total / params.count"
       },
       "type": "bucket_script"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$endpoint count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "repeat": "endpoint",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$endpoint total time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "uri.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$endpoint mean",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      },
      {
       "field": "sum",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "name": "count", "pipelineAgg": "1" },
        { "name": "total", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "params.count == 0 ? 0 : params.total / params.count"
       },
       "type": "bucket_script"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$endpoint count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$endpoint total time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "uri.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$endpoint mean",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      },
      {
       "field": "sum",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "name": "count", "pipelineAgg": "1" },
        { "name": "total", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "params.count == 0 ? 0 : params.total / params.count"
       },
       "type": "bucket_script"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$endpoint count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:CoordinatorController AND instance.keyword:$instance AND uri.keyword:$endpoint",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}