{
 "title": "TC order metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "publish_rate", "query": "20s" },
   {
    "name": "laundry_id",
    "query": "{\"find\":\"terms\", \"field\":\"laundry_id.keyword\"}"
   }
  ]
 },
 "panels": [
  { "title": "Orders metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prediction accuracy mean",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "sum",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "name": "total", "pipelineAgg": "3" },
        { "name": "count", "pipelineAgg": "1" }
       ],
       "settings": {
        "script": "params.count == 0 ? 0 : params.total / params.count"
       },
       "type": "bucket_script"
      }
     ],
     "query": "name:prediction_accuracy",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Max prediction accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:prediction_accuracy",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Prediction error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Max",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:prediction_error",
     "timeField": "@timestamp"
    },
    {
     "alias": "Mean",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sum",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "count",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "name": "total", "pipelineAgg": "1" },
        { "name": "count", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "params.count == 0 ? 0 : params.total / params.count"
       },
       "type": "bucket_script"
      }
     ],
     "query": "name:prediction_error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Submitted, but not completed orders",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$publish_rate", "min_doc_count": 0, "trimEdges": 1 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:orders_submitted",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kafka unsupported events",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:events_unsupported",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Queues ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Queues ratio for laundry with id $laundry_id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "laundry_id",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Actual queue",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:queue_actual",
     "timeField": "@timestamp"
    },
    {
     "alias": "Reserved queue",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:queue_reserved",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}